### ISSUE TITLE
getting: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by batrlatom** [shff/parcel-plugin-purifycss#4]
I am trying it on Ubuntu 18.04 with parcel bundler installed via npm.
I also tried to chmod +777 for all files, but without success. Do you know
ho to get rid of the problem?

**Comment by batrlatom** [comment]
additional error messages:

<--- Last few GCs --->

[30857:0x2765c00]    76069 ms: Mark-sweep 1113.2 (1154.6) -> 1112.6 (1160.1) MB, 412.3 / 0.0 ms  allocation failure GC in old space requested
[30857:0x2765c00]    76479 ms: Mark-sweep 1112.6 (1160.1) -> 1112.5 (1128.6) MB, 410.1 / 0.0 ms  last resort GC in old space requested
[30857:0x2765c00]    76876 ms: Mark-sweep 1112.5 (1128.6) -> 1112.5 (1128.6) MB, 397.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x16c4a72a55e9 <JSObject>
    2: split(this=0x3cb886f026b9 <Very long string[239346023]>)
    3: getAllWordsInContent(aka getAllWordsInContent) [/home/tom/Devel/ai-dev/rcl/client/recall_client/node_modules/purifycss/lib/purifycss.js:787] [bytecode=0x116a83acf539 offset=24](this=0xd0615b022d1 <undefined>,content=0x3cb886f026b9 <Very long string[239346023]>)
    4: purify(aka purify) [/home/tom/Devel/ai-dev/rcl/client/reca...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8d05bc [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x740390842fd

**Comment by shff** [comment]
Hi @batrlatom ! That looks like a problem inside PurifyCSS. It ran out of memory in the `getAllWordsInContent` method, here's the code for it: [/purifycss/purifycss/src/ExtractWordsUtil.js](https://github.com/purifycss/purifycss/blob/master/src/utils/ExtractWordsUtil.js#L5)

Maybe your project is too large and Purify is having a hard time extracting content from it?

Another thing: which root folder is your entry point located in? If it's in the project root folder, PurifyCSS might be peeping inside `node_modules` this will probably take a lot of memory.

I recommend putting your entry point (index.html, index.js, etc) in a separate folder, like `src/` or `app/`. That might fix it!

Unfortunately I believe PurifyCSS isn't maintained anymore. I'm already looking into alternative solutions, such as using PostCSS to do the parsing/cleaning. I made a plugin and published it here. It is compatible with Parcel! https://github.com/shff/postcss-remove-unused-css
