### ISSUE TITLE
"mem" package reported as security vulnerabilities

### ISSUE THREAD

**Issue by nyancodeid** [shff/parcel-plugin-purifycss#5]
Reported from Github Security Alert and Yarn Audit "purify-css" have dependency of "mem" that have security vulnerabilities.

![Screenshot from 2019-12-18 15-03-28](https://user-images.githubusercontent.com/24630806/71067693-9027bd80-21a7-11ea-90cc-eabf51044aa0.png)

![Screenshot from 2019-12-18 14-59-33](https://user-images.githubusercontent.com/24630806/71067393-0a0b7700-21a7-11ea-8371-19177e835fd8.png)

**Comment by shff** [comment]
Yeah, I've been aware of that, but it seems that [purify-css](https://github.com/purifycss/purifycss) is currently unmaintained. If you're interested in the functionality and use Parcel, you can use this: http://github.com/shff/postcss-remove-unused-css

If you have any suggestions on how to fix it from my end without forking, I'm all ears.
